### ISSUE TITLE
Create a basic Go project setup with database client

### ISSUE THREAD

**Issue by robojones** [Gamify-IT/login-backend#1]
### Todo
- [x] set up Go project
- [x] set up Swagger code generation
- [x] set up Prisma code generation
- [x] add GoLand run configuration
- [x] create pipeline to execute tests on pull requests

**Comment by robojones** [comment]
The server is not in a runnable state yet, as it requires a postgres database. I still need to figure out how to open a connection.

**Comment by robojones** [comment]
Apparently, the database connection can be configured using environment variables.
`POSTGRESQL_URL`, `POSTGRES_USER`, `POSTGRES_PASSWORD`

**Comment by robojones** [comment]
I have now added a GoLand run configuration to the project, which starts a database and builds the project. With this run configuration, the project can be started locally.

**Comment by robojones** [comment]
There now is a new Action that executes the tests whenever we push something
